-- The framework file service's schema, as the local `fileservice-postgres` service needs it.
--
-- LOCAL ONLY. Generated by hand from the vendored liquibase changesets in
-- `specs/002-consolidate-progression-leg/contracts/fileservice/` (framework-libraries 58aad8664),
-- which are the authority. This file is the SAME schema those changesets produce on PostgreSQL,
-- written as plain DDL so the container needs no liquibase runtime; it is not a second definition
-- and must be regenerated from them whenever T005 re-vendors the changesets.
--
-- Changeset by changeset, and only the ones that apply to PostgreSQL:
--
--   001-common-initial-schema        content(file_id UUID PK, content BLOB NOT NULL)
--                                    metadata(file_id UUID PK) + FK fk_file_id -> content(file_id)
--   002-postgres-specific            metadata.metadata JSONB NOT NULL
--   003-h2-specific                  dbms="H2" — DOES NOT APPLY here, and is why `metadata` is
--                                    jsonb below rather than text
--   004-add-is-deleted-column        content.deleted BOOLEAN NOT NULL DEFAULT false
--   005-change-content-to-byte-array dbms="postgresql": drops `content` and re-adds it as BINARY,
--                                    i.e. bytea. The re-added column carries NO nullable
--                                    constraint, so 001's NOT NULL is gone and `content` is
--                                    NULLABLE here — deliberately, and not a transcription slip.
--   006-add-date-deleted-column      dbms="postgresql": content.deleted_at TIMESTAMP WITH TIME ZONE
--                                    NULL. NOTE the column is `deleted_at`; only the changeset's
--                                    file name says "date-deleted".
--
-- Deliberately absent: liquibase's own `databasechangelog` / `databasechangeloglock` bookkeeping
-- tables. Nothing this service does reads them, and inventing rows in them would be a fiction about
-- a migration that never ran here.

-- `content` first: `metadata`'s foreign key points at it.
CREATE TABLE content (
    file_id    UUID                     NOT NULL,
    content    BYTEA                    NULL,
    deleted    BOOLEAN                  NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMP WITH TIME ZONE NULL,
    CONSTRAINT content_pkey PRIMARY KEY (file_id)
);

CREATE TABLE metadata (
    file_id  UUID  NOT NULL,
    metadata JSONB NOT NULL,
    CONSTRAINT metadata_pkey PRIMARY KEY (file_id),
    CONSTRAINT fk_file_id FOREIGN KEY (file_id) REFERENCES content (file_id)
);

-- The framework's own repositories insert content before metadata, which the foreign key above
-- requires; `FileServicePayloadStore` does the same, in one transaction.
