package uk.gov.hmcts.cp.courtregister.support;

import static com.github.tomakehurst.wiremock.client.WireMock.aResponse;
import static com.github.tomakehurst.wiremock.client.WireMock.get;
import static com.github.tomakehurst.wiremock.client.WireMock.post;
import static com.github.tomakehurst.wiremock.client.WireMock.postRequestedFor;
import static com.github.tomakehurst.wiremock.client.WireMock.urlEqualTo;
import static com.github.tomakehurst.wiremock.client.WireMock.urlPathMatching;
import static com.github.tomakehurst.wiremock.core.WireMockConfiguration.wireMockConfig;

import com.github.tomakehurst.wiremock.WireMockServer;
import com.github.tomakehurst.wiremock.verification.LoggedRequest;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import javax.sql.DataSource;
import org.springframework.boot.WebApplicationType;
import org.springframework.boot.builder.SpringApplicationBuilder;
import org.springframework.boot.jdbc.DataSourceBuilder;
import org.springframework.context.ConfigurableApplicationContext;
import org.springframework.jdbc.core.simple.JdbcClient;
import tools.jackson.databind.ObjectMapper;
import uk.gov.hmcts.cp.Application;
import uk.gov.hmcts.cp.courtregister.adapter.systemdocgenerator.SystemDocGeneratorClient;
import uk.gov.hmcts.cp.courtregister.config.JacksonConfig;

/**
 * Everything the nightly run talks to, for the two end-to-end suites that drive it.
 *
 * <p>The run has four outsides and this fixture is three of them: App Configuration, from which the
 * one lever is read; systemdocgenerator's command and query APIs; and the framework file service's
 * own database, which the payload is written into and which nothing in this service migrates. The
 * fourth is the broker, and each suite owns that itself because whether an outcome is published at
 * all is the thing those suites differ about.
 *
 * <p><strong>One WireMock server, two contexts.</strong> The App Configuration {@code kv} resource
 * and systemdocgenerator's two paths are disjoint, so one server can be both; two would be two
 * ports, two lifecycles and two chances to reset the wrong one. What it buys is the assertion
 * {@code FlagGateEndToEndIT} exists to make - that a run the flag stopped reached <em>no</em>
 * socket - because "nothing was requested" is a claim about the one server that would have received
 * it.
 *
 * <p>The flag is read through a real {@code AppConfigurationFlagReader} over a real SDK client; only
 * the credential is a connection string rather than this pod's workload identity, because a token
 * endpoint is the one part of that read no suite can stand up (see
 * {@code GenerationStackConfiguration}).
 *
 * <p>The file-service database is its own database inside the shared container, named apart from
 * {@code FileServicePayloadStoreIT}'s so the two suites can run in one JVM without one creating a
 * database the other already made.
 */
public final class GenerationStackSupport implements AutoCloseable {

    /** The file-service database this fixture creates, seeded from the committed local schema. */
    public static final String DATABASE = "fileservice_e2e";

    /** The identity the App Configuration client authenticates with; a test value and no secret. */
    public static final String STORE_ID = "0-l0-s0:courtregistertest";

    /** The HMAC secret that identity signs with; a fixed, published test value. */
    public static final String STORE_SECRET =
            "c2VydmljZS1jcC1jcmltZS1jb3VydC1yZWdpc3Rlci10ZXN0LXNlY3JldA==";

    /** The App Configuration key the flag is read under, as the deployment configures it. */
    public static final String FLAG_KEY = ".appconfig.featureflag/CourtRegisterService";

    /** The label one store serves this stack under. */
    public static final String FLAG_LABEL = "e2e";

    /** Any {@code kv} read, whatever key and label the reader asks under. */
    private static final String ANY_KEY_PATH = "/kv/.*";

    /** The media type App Configuration answers a key-value read with. */
    private static final String KV_MEDIA_TYPE = "application/vnd.microsoft.appconfig.kv+json";

    private static final ObjectMapper MAPPER = JacksonConfig.contractObjectMapper();

    /** The committed local schema, generated by hand from the vendored liquibase changesets. */
    private static final Path FILE_SERVICE_SCHEMA = Path.of("docker", "fileservice", "init.sql");

    /** The file-service database's URL, created once per JVM however many suites ask for it. */
    private static String fileServiceDatabaseUrl;

    private final WireMockServer contexts;

    private final JdbcClient fileService;

    private GenerationStackSupport(final WireMockServer contexts, final JdbcClient fileService) {
        this.contexts = contexts;
        this.fileService = fileService;
    }

    /**
     * Starts the two HTTP contexts and makes sure the file-service database exists.
     *
     * @return the running stack, to be closed by the caller
     */
    public static GenerationStackSupport start() {
        final WireMockServer contexts = new WireMockServer(wireMockConfig().dynamicPort());
        contexts.start();
        final GenerationStackSupport stack =
                new GenerationStackSupport(contexts, JdbcClient.create(fileServiceDataSource()));
        stack.sdgAcceptsEveryRequest();
        return stack;
    }

    /**
     * The settings that point a context at this stack.
     *
     * <p>Generation on and every mode LIVE, because that is the deployment these suites are about
     * and {@code PropertiesValidator} refuses a stand-in wherever generation is enabled. Intake is
     * off: it is the other half of the service and needs a broker these suites have no business
     * standing up. The broker settings are the caller's, because whether an outcome is published is
     * what the two suites differ about.
     *
     * @return the settings
     */
    public Map<String, String> settings() {
        final Map<String, String> settings = new LinkedHashMap<>();
        settings.put("spring.datasource.url", PostgresTestSupport.jdbcUrl());
        settings.put("spring.datasource.username", PostgresTestSupport.username());
        settings.put("spring.datasource.password", PostgresTestSupport.password());
        settings.put("courtregister.consumer.enabled", "false");
        settings.put("courtregister.payload.mode", "STUB");
        settings.put("courtregister.referencedata.mode", "STUB");
        settings.put("courtregister.generation.enabled", "true");
        settings.put("courtregister.generation.completion", "event");
        settings.put("courtregister.generation.sdg-mode", "LIVE");
        settings.put("courtregister.generation.nn-mode", "LIVE");
        settings.put("courtregister.generation.fileservice-mode", "LIVE");
        settings.put("courtregister.generation.flag-mode", "LIVE");
        settings.put("courtregister.feature.endpoint", contexts.baseUrl());
        settings.put("courtregister.feature.key", FLAG_KEY);
        settings.put("courtregister.feature.label", FLAG_LABEL);
        settings.put("courtregister.feature.timeout", "5s");
        settings.put("courtregister.fileservice.url", fileServiceUrl());
        settings.put("courtregister.fileservice.username", PostgresTestSupport.username());
        settings.put("courtregister.fileservice.password", PostgresTestSupport.password());
        settings.put("courtregister.endpoints.systemdocgenerator", contexts.baseUrl());
        settings.put("courtregister.endpoints.notificationnotify", contexts.baseUrl());
        settings.put("courtregister.endpoints.system-user-id", ServiceTestSupport.SYSTEM_USER_ID);
        settings.put("courtregister.email.templates.cr_standard",
                "5c9a0e21-3d47-4f18-9b62-0a71c4e8d530");
        // An in-VM Artemis, which is the whole of the broker these suites need: the subscription is
        // durable and topic-scoped exactly as it is deployed, and nothing outside this JVM can
        // publish onto it.
        settings.put("spring.artemis.mode", "embedded");
        settings.put("spring.artemis.embedded.enabled", "true");
        settings.put("spring.artemis.embedded.topics", "public.event");
        // Never connected to - embedded mode dials vm://0 - but startup requires a broker URL
        // wherever completion is event-driven, and it is right to.
        settings.put("spring.artemis.broker-url", "tcp://localhost:61616");
        // The one bean these suites replace, and the reason: a workload-identity credential needs a
        // token endpoint, which is the one leg of the flag read no fixture can stand up.
        settings.put("spring.main.allow-bean-definition-overriding", "true");
        return settings;
    }

    /** Where this stack's App Configuration and systemdocgenerator answer. */
    public String baseUrl() {
        return contexts.baseUrl();
    }

    /**
     * Starts the service against this stack, with the flag reader these suites can point at a stub.
     *
     * <p>The settings go down as command-line arguments for the reason
     * {@link ServiceTestSupport#start(Map)} gives: default properties sit <em>below</em>
     * {@code application.yaml}, so a suite pointing the service at a container would silently be
     * answered by the committed local development value.
     *
     * @param settings this stack's settings, with whatever the suite added to them
     * @return the running context, to be closed by the caller
     */
    public static ConfigurableApplicationContext startService(final Map<String, String> settings) {
        return new SpringApplicationBuilder(Application.class, GenerationStackConfiguration.class)
                .web(WebApplicationType.NONE)
                .run(settings.entrySet().stream()
                        .map(setting -> "--" + setting.getKey() + '=' + setting.getValue())
                        .toArray(String[]::new));
    }

    // --- the one lever ---------------------------------------------------------------------------

    /**
     * App Configuration answers with the flag, enabled or not.
     *
     * @param enabled what the store says the flag is
     */
    public void flagIs(final boolean enabled) {
        answering(200, settingCarrying(flagValue(enabled)));
    }

    /** App Configuration is there and cannot answer, which the reader reads as UNREADABLE. */
    public void flagIsUnreadable() {
        answering(500, "{\"error\":\"the store could not answer\"}");
    }

    private void answering(final int status, final String body) {
        contexts.stubFor(get(urlPathMatching(ANY_KEY_PATH)).willReturn(aResponse()
                .withStatus(status)
                .withHeader("Content-Type", KV_MEDIA_TYPE)
                .withBody(body)));
    }

    /** The store's answer for a setting that is there, carrying {@code value} verbatim. */
    private static String settingCarrying(final String value) {
        return "{\"key\":" + MAPPER.writeValueAsString(FLAG_KEY)
                + ",\"label\":" + MAPPER.writeValueAsString(FLAG_LABEL)
                + ",\"content_type\":\"application/vnd.microsoft.appconfig.ff+json\""
                + ",\"value\":" + MAPPER.writeValueAsString(value)
                + ",\"tags\":{},\"locked\":false"
                + ",\"last_modified\":\"2026-09-01T18:00:00+00:00\",\"etag\":\"cr-e2e\"}";
    }

    /** App Configuration's feature-flag JSON, as the vendored value schema declares it. */
    private static String flagValue(final boolean enabled) {
        return "{\"id\":\"CourtRegisterService\",\"description\":\"the e2e stack's flag\""
                + ",\"enabled\":" + enabled
                + ",\"conditions\":{\"client_filters\":[]}}";
    }

    // --- systemdocgenerator ----------------------------------------------------------------------

    /** systemdocgenerator accepts every render request, which is the only success the contract has. */
    public void sdgAcceptsEveryRequest() {
        contexts.stubFor(post(urlEqualTo(SystemDocGeneratorClient.COMMAND_PATH))
                .willReturn(aResponse().withStatus(202)));
    }

    /**
     * Every {@code generate-document} this stack has been sent, as bodies.
     *
     * @return the request bodies, in arrival order
     */
    public List<String> renderRequests() {
        return contexts.findAll(postRequestedFor(
                        urlEqualTo(SystemDocGeneratorClient.COMMAND_PATH)))
                .stream()
                .map(LoggedRequest::getBodyAsString)
                .toList();
    }

    // --- the file service ------------------------------------------------------------------------

    /**
     * Whether the payload rows for a file id are both there.
     *
     * @param fileId the id the batch minted
     * @return true where the {@code content} and {@code metadata} rows both exist
     */
    public boolean payloadStoredUnder(final UUID fileId) {
        return rows("SELECT count(*) FROM content WHERE file_id = :fileId", fileId) == 1
                && rows("SELECT count(*) FROM metadata WHERE file_id = :fileId", fileId) == 1;
    }

    /**
     * The metadata row written beside a payload.
     *
     * @param fileId the id the batch minted
     * @return the metadata JSON, or empty where there is no row
     */
    public String metadataUnder(final UUID fileId) {
        return fileService.sql("SELECT metadata::text FROM metadata WHERE file_id = :fileId")
                .param("fileId", fileId)
                .query(String.class)
                .optional()
                .orElse("");
    }

    private long rows(final String sql, final UUID fileId) {
        return fileService.sql(sql).param("fileId", fileId).query(Long.class).single();
    }

    // --- lifecycle -------------------------------------------------------------------------------

    /** Forgets every stub and every recorded request, and puts the SDG catch-all back. */
    public void reset() {
        contexts.resetAll();
        sdgAcceptsEveryRequest();
    }

    @Override
    public void close() {
        contexts.stop();
    }

    /**
     * The file-service database, created and seeded once per JVM.
     *
     * <p>Its own database rather than the shared one, because this service is write-only against a
     * schema it does not own and mixing the framework's two tables into the processed log's database
     * would make the second datasource a fiction.
     */
    private static synchronized String fileServiceUrl() {
        if (fileServiceDatabaseUrl == null) {
            final String url = PostgresTestSupport.createEmptyDatabase(DATABASE);
            applyFileServiceSchema(url);
            fileServiceDatabaseUrl = url;
        }
        return fileServiceDatabaseUrl;
    }

    private static DataSource fileServiceDataSource() {
        return DataSourceBuilder.create()
                .url(fileServiceUrl())
                .username(PostgresTestSupport.username())
                .password(PostgresTestSupport.password())
                .build();
    }

    private static void applyFileServiceSchema(final String url) {
        final String ddl;
        try {
            ddl = Files.readString(FILE_SERVICE_SCHEMA, StandardCharsets.UTF_8);
        } catch (final IOException unreadable) {
            throw new IllegalStateException("could not read " + FILE_SERVICE_SCHEMA, unreadable);
        }
        try (Connection connection = DriverManager.getConnection(
                        url, PostgresTestSupport.username(), PostgresTestSupport.password());
                Statement statement = connection.createStatement()) {
            statement.execute(ddl);
        } catch (final SQLException failed) {
            throw new IllegalStateException(
                    "could not apply " + FILE_SERVICE_SCHEMA + " to " + url, failed);
        }
    }
}
